on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Install poetry
        if: ${{ steps.release.outputs.release_created }}
        run: pipx install poetry
      - uses: actions/setup-python@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: '3.11'
      - run: poetry install --without dev
        if: ${{ steps.release.outputs.release_created }}
      - run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_PASSWORD }}
        if: ${{ steps.release.outputs.release_created }}
