name: Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: poetry install
      - name: Run tests
        run: poetry run pytest
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          USERNAME: ${{ secrets.USERNAME }}
          USERNAME2: ${{ secrets.USERNAME2 }}
          PASSWORD: ${{ secrets.PASSWORD }}
          OTPCODE: ${{ secrets.OTPCODE }}
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
