name: Update docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Create md files
        run: sphinx-build -M markdown ./docs_source ./docs
      - name: Update docs website
        uses: car-on-sale/action-pull-request-another-repo@v1.04
        env:
          API_TOKEN_GITHUB: ${{ secrets.WEBSITE_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.WEBSITE_GITHUB_TOKEN }}
        with:
          source_folder: 'docs/markdown'
          destination_repo: 'ScribeLabsAI/documentation'
          destination_folder: 'docs/SDK/auth-python'
          destination_base_branch: 'master'
          destination_head_branch: 'auth-python-update'
          commit_msg: 'docs(authPython): Update Auth Python doc'
          pr_title: 'Update Auth Python doc'
          pull_request_reviewers: 'EHadoux'
          user_email: 'ailin@scribelabs.ai'
          user_name: 'ailinvenerus'
