name: Update docs

on:
  release:
    types: [published]

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Create md files
        run: sphinx-build -M markdown ./docs_source ./docs

  update-docs:
    runs-on: ubuntu-latest
    needs: create-files
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update docs website
        uses: car-on-sale/action-pull-request-another-repo@v1.3.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.WEBSITE_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.WEBSITE_GITHUB_TOKEN }}
        with:
          source_folder: 'docs/markdown'
          destination_repo: 'ScribeLabsAI/documentation'
          destination_folder: 'docs/SDK/auth-python'
          destination_base_branch: 'master'
          destination_head_branch: 'auth-python-update'
          commit_msg: 'docs(authPython): Update Auth Python doc'
          pr_title: 'Update Auth Python doc'
          pull_request_reviewers: 'EHadoux'
          user_email: 'ailin@scribelabs.ai'
          user_name: 'ailinvenerus'